on:
  release:
    types: [published]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cargo update --verbose
    - name: Run tests
      run: cargo test --verbose

  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build application
      run: cargo build --verbose

  publish:
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to crates.io
      env: 
        CARGO_API_KEY: ${{ secrets.CRATES_IO_API_KEY }}
      run: cargo login $CARGO_API_KEY
    - name: Publish crate
      run: cargo publish
